---
version: 2
jobs:
  build:
    docker:
      - image: quay.io/freedomofpress/circleci-docker:latest
    working_directory: ~/ansible-role-tomb

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: pip install -r requirements.txt

      - setup_remote_docker

      - run:
          name: Test role
          command: molecule test
